FROM ubuntu:latest

WORKDIR /app

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y nano
RUN apt-get install -y python3-pip python3-dev python3-venv

COPY ./parser/requirements.txt /app/requirements.txt

SHELL ["/bin/bash", "-c"]
# RUN rm -r /app/venv
RUN python3 -m venv /app/venv-docker
RUN source /app/venv-docker/bin/activate && pip3 install --upgrade pip && pip3 install -r /app/requirements.txt

RUN groupadd appgroup
RUN useradd --create-home --shell /bin/bash app -g appgroup

COPY ./parser /app

RUN chown app:appgroup -R /app
RUN chmod 700 -R /app

EXPOSE 5000

USER app

ENTRYPOINT ["/bin/bash", "-c", "/app/run.sh"]
# ENTRYPOINT ["/bin/bash", "-c", "sleep infinity"]